import { Task } from '../types/task'

export const mockTasks: Task[] = [
  {
    id: '1',
    title: '完成编程导航网站首页重构',
    description: '优化首页布局，提升用户体验',
    category: '项目',
    priority: '高',
    status: 'pending',
    createdAt: '2026-01-12T00:00:00.000Z',
  },
  {
    id: '2',
    title: '录制 Vibe Coding 教程视频',
    description: '第5集：AI 应用开发实战',
    category: '工作',
    priority: '高',
    status: 'pending',
    createdAt: '2026-01-12T00:00:00.000Z',
  },
  {
    id: '3',
    title: '阅读《代码整洁之道》第3章',
    description: '学习函数设计的最佳实践',
    category: '学习',
    priority: '中',
    status: 'completed',
    createdAt: '2026-01-11T00:00:00.000Z',
  },
  {
    id: '4',
    title: '优化代码生成器性能',
    description: '减少生成时间，提升响应速度',
    category: '项目',
    priority: '中',
    status: 'pending',
    createdAt: '2026-01-13T00:00:00.000Z',
  },
  {
    id: '5',
    title: '整理技术文档',
    description: '更新项目 README 和 API 文档',
    category: '工作',
    priority: '低',
    status: 'pending',
    createdAt: '2026-01-14T00:00:00.000Z',
  },
  {
    id: '6',
    title: '学习 TypeScript 高级特性',
    description: '深入理解泛型和类型推断',
    category: '学习',
    priority: '中',
    status: 'pending',
    createdAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: '7',
    title: '健身锻炼',
    description: '每周三次有氧运动',
    category: '生活',
    priority: '低',
    status: 'completed',
    createdAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: '8',
    title: '购买生活用品',
    description: '牛奶、鸡蛋、面包',
    category: '生活',
    priority: '中',
    status: 'pending',
    createdAt: '2026-01-16T00:00:00.000Z',
  },
]